### ISSUE TITLE
http functions

### ISSUE THREAD

**Issue by Divity** [fedddddd/t5-gsc-utils#5]
the ability to send events to discord via webhooks through gsc

**Comment by Divity** [comment]
Also idk if this would be the same thing. An openlink function to open the browser of a client

**Comment by fedddddd** [comment]
> Also idk if this would be the same thing. An openlink function to open the browser of a client

That cannot be added through a plugin and allowing a server to open a client's browser is very bad and should not be possible.

**Comment by Divity** [comment]
> 

ill definitely be content with webhook stuff

**Comment by fedddddd** [comment]
An example on how to send webhook requests:
```gsc
init()
{
    url = "your webhook url";

    options = [];
    options["headers"] = [];
    options["headers"]["Content-Type"] = "application/json";
    options["body"] = "{\"username\": \"test\", \"content\": \"hello world\", \"avatar_url\": \"\"}";

    req = http::request(url, options);
    req waittill("done", data, success, error);
    print(data, success, error);
}
```
